### ISSUE TITLE
crash on command

### ISSUE THREAD

**Issue by Bergiu** [TheWildBear/bigDataTelgrambot#1] opened 2017-12-19 20:44 UTC
It crashes on the command `/count 'something`

**Comment by geozukunft** [comment] 2017-12-19 20:56
That's a huge problem 😂😂

**Comment by toniy0** [comment] 2017-12-19 21:20
pls fix ......

**Comment by shenef** [comment] 2017-12-19 21:48
It will be permanently down if certain people notice that

**Comment by TheWildBear** [comment] 2017-12-20 15:12
Duplicate of #2 
same as #3

**Closed as completed by TheWildBear** 2017-12-20 15:12 UTC
Labels: bug
